# site settings
title: Stealth
subtitle: Byte
email: youremailaddress@gmail.com
description: ./execute 0x41 * 4000
baseurl: '' # the subpath of your site, e.g. /blog
url: https://stealthbyte.github.io # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles -- increment tiles-count every time you add a new post
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 7


# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 

# build settings
markdown: kramdown
highlighter: pygments

sass:
  style: compressed
